# C++ project
language: cpp
sudo: required
dist: xenial
install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get -q update
  - sudo apt-get -y install libboost-dev libboost-serialization-dev gdal-bin libgdal-dev make cmake
script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make -j 4
  - ./fmm
  - ./stmatch
  - ./ubodt_gen
branches:
  only:
  - master
  - osm
